package br.ufmg.engsoft.reprova.model;

public class ReprovaModel {
	
	/**
	 * Unique id of the model. When null, the id will be automatically generated by
     * the database.
	 */
	protected String id;
	
	public void setId(String id) {
		this.id = id;
	}
	
	public String getId() {
		return id;
	}

}
